<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/NestedAdminMasterPage.Master" AutoEventWireup="true" CodeBehind="EditImages.aspx.cs" Inherits="WebGallery.Admin.EditImages" %>

<asp:Content ContentPlaceHolderID="NestedContentPlaceHolder" runat="server">

    <link href="../Content/editimages.css" rel="stylesheet" />

    <asp:ScriptManager runat="server"></asp:ScriptManager>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>

            <asp:GridView
                ClientIDMode="Static"
                DataKeyNames="PictureID"
                ItemType="WebGallery.ViewModel.PictureViewModel"
                SelectMethod="GetAllPictures"
                ID="GridView1"
                runat="server"
                Width="600px"
                AutoGenerateColumns="False"
                EmptyDataText="There are no data records to display."
                BackColor="White"
                BorderColor="#336666"
                BorderStyle="Double"
                BorderWidth="3px"
                CellPadding="4"
                GridLines="Horizontal"
                OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                <Columns>
                    <asp:CommandField ShowSelectButton="True" />

                    <asp:TemplateField HeaderText="Название">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtTitleEdit" runat="server" Text='<%# BindItem.Name %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblTitle" runat="server" Text='<%#  Item.Name %>' />
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Описание">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtDescriptionEdit" runat="server" Text='<%# BindItem.Description %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblDescription" runat="server" Text='<%# Item.Description %>' />
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Изображение">
                        <EditItemTemplate>
                            <img alt="iii" id="Image1" runat="server" height='100' src='<%# Item.ThumbnailImagePath %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <img alt="iii" id="Image1" runat="server" height='100' src='<%# Item.ThumbnailImagePath %>' />
                        </ItemTemplate>
                    </asp:TemplateField>

                </Columns>
                <FooterStyle BackColor="White" ForeColor="#333333" />
                <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="White" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F7F7F7" />
                <SortedAscendingHeaderStyle BackColor="#487575" />
                <SortedDescendingCellStyle BackColor="#E5E5E5" />
                <SortedDescendingHeaderStyle BackColor="#275353" />
            </asp:GridView>

            <asp:DetailsView
                ClientIDMode="Static"
                CommandRowStyle-Font-Bold="true"
                AutoGenerateEditButton="true"
                AutoGenerateDeleteButton="true"
                ItemType="WebGallery.ViewModel.PictureViewModel"
                ID="DetailsView1"
                runat="server"
                Height="50px"
                Width="400px"
                AutoGenerateRows="False"
                BackColor="#DEBA84"
                BorderColor="#DEBA84"
                BorderStyle="None"
                BorderWidth="1px"
                CellPadding="3"
                CellSpacing="2"
                OnItemDeleting="DetailsView1_ItemDeleting"
                OnItemUpdating="DetailsView1_ItemUpdating"
                OnModeChanging="DetailsView1_ModeChanging">

                <EmptyDataTemplate>
                    Выберете в таблице слева обьект для редактирования
                </EmptyDataTemplate>
                <EditRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                <Fields>

                    <asp:TemplateField>
                        <EditItemTemplate>
                            <img runat="server" height='200' src='<%# Item.ThumbnailImagePath %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <img runat="server" height='200' src='<%# Item.ThumbnailImagePath %>' />
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:BoundField DataField="Name" HeaderText="Название" />
                    <asp:BoundField DataField="Description" HeaderText="Описание" />


                </Fields>
                <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
                <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
            </asp:DetailsView>

        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
